langzeitevent:
  enable: false
  worldname: ''
  consume_blacklist:
  - PORK
  command_whitelist:
  - SPAWN
websigns:
  forum: http://forum.creepercantine.de
  webseite: http://creepercantine.de
  regeln: http://creepercantine.de/regeln/