langzeitevent:
  enable: false
  worldname: ''
  consume_blacklist:
  - GRILLED_PORK
  command_whitelist:
  - SPAWN
  - LE_LEAVE
  - WARP_SPAWN
websigns:
  forum: http://forum.creepercantine.de
  webseite: http://creepercantine.de
  regeln: http://creepercantine.de/regeln/